import { NextResponse } from 'next/server';
import JSZip from 'jszip';

export async function POST(request) {
  try {
    const { codeFiles, repoInfo } = await request.json();
    
    // Create a new ZIP file
    const zip = new JSZip();
    
    // Add each code file to the ZIP
    Object.keys(codeFiles).forEach(filePath => {
      const file = codeFiles[filePath];
      const content = file.content || file;
      zip.file(filePath, content);
    });
    
    // Add a README file
    const readmeContent = `# ${repoInfo.name}

${repoInfo.description || 'Portfolio website'}

## Getting Started

1. Open index.html in your browser
2. Customize the content as needed
3. Deploy to your preferred hosting platform

## Files

${Object.keys(codeFiles).map(file => `- ${file}`).join('\n')}

Generated by CraftMyFolio
`;
    
    zip.file('README.md', readmeContent);
    
    // Generate the ZIP file
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' });
    
    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${repoInfo.name}-portfolio.zip"`
      }
    });
  } catch (error) {
    console.error('Error creating download package:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to create download package' },
      { status: 500 }
    );
  }
}