// Gemini AI API Integration
const GEMINI_API_KEY = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';


export async function generatePortfolioContent(userInput) {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key not configured');
  }
  
  console.log('API Key configured:', !!GEMINI_API_KEY);
  console.log('User input length:', userInput?.length || 0);

  const prompt = `You are an expert portfolio creator AI. Based on the user's information, provide helpful guidance for creating a professional portfolio.

User input: ${userInput}

Please respond as a helpful AI assistant that:
1. Asks relevant follow-up questions about their profession, skills, and projects
2. Provides specific suggestions for portfolio sections
3. Recommends design themes based on their field
4. Helps organize their content effectively

Keep responses conversational, encouraging, and under 150 words.`;

  try {
    console.log('Making request to:', GEMINI_API_URL);
    
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 500,
        },
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          }
        ]
      })
    });

    console.log('Response status:', response.status);
    console.log('Response headers:', response.headers);

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error:', errorText);
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    console.log('Full API response:', data);
    
    // Check if response is empty or malformed
    if (!data || Object.keys(data).length === 0) {
      console.error('Empty API response received');
      throw new Error('Empty response from Gemini API');
    }
    
    // Check for error in response
    if (data.error) {
      console.error('API error:', data.error);
      throw new Error(`Gemini API error: ${data.error.message || 'Unknown error'}`);
    }
    
    // Validate expected response structure
    if (!data.candidates || !Array.isArray(data.candidates) || data.candidates.length === 0) {
      console.error('No candidates in response:', data);
      throw new Error('No content generated by Gemini API');
    }
    
    const candidate = data.candidates[0];
    
    // Extract text content with fallback
    const text = candidate.content?.parts?.[0]?.text;
    
    if (text) {
      return text;
    }
    
    // Fallback response for any content extraction failure
    return `Thank you for sharing that information! I can help you create a professional portfolio. Let me ask a few questions:

1. What specific projects would you like to highlight?
2. What's your target audience?
3. Any design preferences?

Feel free to share more details!`;
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    
    // Provide a fallback response for better user experience
    if (error.message.includes('Empty response') || error.message.includes('Invalid response')) {
      return `Thank you for sharing that information! Based on what you've told me, I can help you create a professional portfolio. Let me ask a few questions to better understand your needs:

1. What specific projects or achievements would you like to highlight?
2. What's your target audience (employers, clients, etc.)?
3. Do you have any design preferences or color schemes in mind?

Feel free to share more details about your background and goals!`;
    }
    
    throw error;
  }
}

export async function generatePortfolioStructure(conversationHistory) {
  if (!GEMINI_API_KEY) {
    throw new Error('Gemini API key not configured');
  }

  const prompt = `Based on this conversation history, generate a complete portfolio structure in JSON format:

${conversationHistory.map(msg => `${msg.type}: ${msg.content}`).join('\n')}

Return ONLY a valid JSON object with this exact structure:
{
  "personalInfo": {
    "name": "User Name",
    "title": "Professional Title",
    "bio": "Professional bio",
    "contact": {}
  },
  "sections": [
    {
      "type": "hero",
      "title": "Welcome",
      "content": "Hero section content"
    },
    {
      "type": "about",
      "title": "About Me",
      "content": "About section content"
    },
    {
      "type": "skills",
      "title": "Skills",
      "items": ["Skill1", "Skill2"]
    },
    {
      "type": "projects",
      "title": "Projects",
      "items": [{"name": "Project Name", "description": "Description", "technologies": ["Tech1"]}]
    }
  ],
  "theme": {
    "primaryColor": "#3b82f6",
    "style": "modern"
  }
}`;

  try {
    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.3,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 1000,
        },
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          }
        ]
      })
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Gemini API error details:', errorData);
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    
    // Check if response is empty or malformed
    if (!data || Object.keys(data).length === 0) {
      console.error('Empty API response received');
      throw new Error('Empty response from Gemini API');
    }
    
    // Check for error in response
    if (data.error) {
      console.error('API error:', data.error);
      throw new Error(`Gemini API error: ${data.error.message || 'Unknown error'}`);
    }
    
    // Validate expected response structure
    if (!data.candidates || !Array.isArray(data.candidates) || data.candidates.length === 0) {
      console.error('No candidates in response:', data);
      throw new Error('No content generated by Gemini API');
    }
    
    const candidate = data.candidates[0];
    
    if (!candidate.content?.parts?.[0]?.text) {
      console.error('No text content in candidate:', candidate);
      throw new Error('No text content in Gemini API response');
    }
    
    const jsonString = candidate.content.parts[0].text;
    
    // Extract JSON from the response
    const jsonMatch = jsonString.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
    
    throw new Error('Invalid JSON response from Gemini');
  } catch (error) {
    console.error('Error generating portfolio structure:', error);
    throw error;
  }
}